config/routes.rb
Rails.application.routes.draw do
  
  resources :concerts do
  	resources :comments
  end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :concert
	validates :comment, presence: true

	validates :concert, presence: true


end

app/models/concert.rb
class Concert < ActiveRecord::Base
	has_many :comments
	validates :band, :venue, :city, :date, :description, presence: true
	validates :price, presence: true
	# , numericality: {greater_than: 0}

	def self.get_events_today
		where("date = ?", Date.today)
	end

	def self.get_concert id
		where("id = ?", id).first
	end

	def self.next_concerts
		where("date > ? and date < ?", DateTime.now, DateTime.now.end_of_month)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	def index
		@id = params[:concert_id]
		@concert = Concert.find_by(id: @id)
		# binding.pry
		@comments = @concert.comments
		@band = @concert.band
	end

	def new
		@concert = Concert.find params[:concert_id]
		@comment = @concert.comments.new
	end

	def create
		@concert = Concert.find params[:concert_id]
		@comment = @concert.comments.new comment_params
		if @comment.save
			redirect_to concert_comments_path(@concert)
		else
			@errors = @comment.errors.full_messages
			render 'new'
		end
	end


	private
	def comment_params
		return params.require(:comment).permit(:comment)
	end

end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

	def index
		@concerts = Concert.get_events_today
		@next_concerts = Concert.next_concerts
	end

	def new
		@concert = Concert.new
	end

	def create
		@concert = Concert.new concert_params
		if @concert.save
			redirect_to concerts_path
		else
			@errors = @concert.errors.full_messages
			render 'new'
		end
	end

	def show
		@concert = Concert.get_concert params[:id]
	end


	private
	def concert_params
		return params.require(:concert).permit(:band, :venue, :city, :date, :price, :description)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/comments/index.html.erb
<h1><%= @band %></h1>
<ul>
<% @comments.each do |comment| %>
	<li><%= comment.id %> - <%= comment.comment %></li>
<% end %>
</ul>
<%= link_to("New comment", concert_comments_path(@concert.id)) %>
<%= link_to("Concerts", concerts_path) %>

app/views/comments/new.html.erb
<%= form_for [@concert, @comment] do |f| %>
<%= f.label :comment %>
<%= f.text_field :comment %>
<br>
<%= f.submit 'Save' %>
<%= link_to("Cancel", concert_comments_path(@concert.id)) %>
<% end %>

app/views/concerts/index.html.erb
<h1>Today concerts</h1>

<ul>
<% @concerts.each do |concert| %>
	<li><%= link_to(concert.band, concert_path(concert)) %></a> - <%= concert.description %></li>
<% end %>
<h2>Next concerts in the current month</h2>
<% @next_concerts.each do |concert| %>
	<li><%= link_to(concert.band, concert_path(concert)) %></a> - <%= concert.description %></li>
<% end %>
<%= link_to("New concert", new_concert_path) %>
</ul>

app/views/concerts/new.html.erb
<h1>New concert</h1>

<%= form_for @concert do |f| %>
<%= f.label :band %>
<%= f.text_field :band %>
<br>
<%= f.label :venue %>
<%= f.text_field :venue %>
<br>
<%= f.label :city %>
<%= f.text_field :city %>
<br>
<%= f.label :date %>
<%= f.date_field :date %>
<br>
<%= f.label :price %>
<%= f.number_field :price %>
<br>
<%= f.label :description %>
<%= f.text_field :description %>
<br>
<%= f.submit 'Create' %>
<%= link_to("Cancel", concerts_path) %>
<% end %>

app/views/concerts/show.html.erb
<h1><%= @concert.band %></h1>

<ul>
	<li>Description: <%= @concert.description %></li>
	<li>Date: <%= @concert.date %></li>
	<li>Address: <%= @concert.city %> - <%= @concert.venue %></li>
	<li>Price: <%= @concert.price %> €</li>
</ul>
<%= link_to("Concerts", concerts_path) %>
<%= link_to("New comment", new_concert_comment_path(@concert)) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MCN</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<h1 class="main-title">MCN</h1>
	</header>
<%= yield %>
	<footer>
			<p class="footer-text">By Ángel Villalba</p>
	</footer>
</body>
</html>